title: Daniel H채ll
description: > # this means to ignore newlines until "baseurl:"
  A protfolio created by Daniel H채ll for variour projects, hosted by github pages.
permalink: ':title/'
baseurl: "/portfolio" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Daniel H채ll # add your name
author-img: daniel_hall.jpg # add your photo
about-author: I am a C developer, highly interested in performance and optimisation techniques. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: Danhall01 # add your Github handle
social-linkedin: daniel-h채ll-020825218 # add your Linkedin handle
social-email: dahl20@student.bth.se # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
